version: "2"
services:
    eureka-server:
      build: ./eureka-server
      network_mode: host
      restart: always

    api-server:
      build: ./zuul-api-gateway
      network_mode: host
      restart: always

    track-service:
      build: ./music-service
      network_mode: host
      depends_on:
        - config-server
      restart: always

    user-service:
      build: ./user-service
      network_mode: host
      depends_on:
        - config-server
      restart: always

    config-server:
      build: ./spring-config-server
      network_mode: host
      restart: always

    mysql:
      image: mysql:5.7
      #    ports:
      #      - 3306:3306
      #    expose:
      #      - 3306
      container_name: mysql
      environment:
        MYSQL_ROOT_PASSWORD: root123
        MYSQL_DATABASE: Userservice
        MYSQL_PASSWORD: root123
        MYSQL_USER: root
      network_mode: host
#      hostname: localhost
      restart: always
      ports:
        - 3306:3306
      volumes:
        - /$HOME/mysql:/var/lib/mysql

    mongo:
      image: mongo
      container_name: mongo
      network_mode: host
      hostname: localhost
      restart: always
      volumes:
        - /$HOME/mongo:/var/lib/mongo